language: ruby
cache: bundler
rvm:
  - 2.1.5
  - 2.2.0
before_install:
  - sudo apt-get update && sudo apt-get install libicu-dev
before_script:
  - mysql -e 'create database enju_test'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  slack:
    secure: ZbjsNTloRj5xbP5nRcwrqAJKC+6Kwo4M+J7Z+aXcHtKTzWfxfJw/aN47CrLm1afd8m+JPgEP3FjsXkOSBxfHiSwitZv4F6PjDaNcRXsv6gMI4dI+AhGTeXQuGtXDdYljipMVYAg0+Og3aVV7ZyesiugkLLMGV5d0TF/7mSVbWVs=
addons:
  code_climate:
    repo_token: c193cb8ea058a7d62fd62d6d05adaaf95f6bdf882c1039500b30b54494a36e52
