language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
before_script: "bundle exec rake db:migrate"
branches:
  only:
    - master
    - "1.1"
services:
  - redis-server
gemfiles:
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_1.gemfile
