language: ruby
rvm:
  - 1.9.3
  - 2.0.0
<<<<<<< HEAD
  - 2.1.2
=======
  - 2.1.3
>>>>>>> 1.1
before_script: "bundle exec rake db:migrate"
branches:
  only:
    - master
<<<<<<< HEAD
    - 1.1
services:
  - elasticsearch
  - redis-server
=======
    - "1.1"
services:
  - redis-server
gemfile:
  - gemfiles/rails3_2.gemfile
  - gemfiles/rails4_1.gemfile
>>>>>>> 1.1
